// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

package io.yottachain.nodemgmt.analysis.pb;

public interface GetRebuildItemRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pbanalysis.GetRebuildItemResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.pbanalysis.NodeMsg node = 1;</code>
   */
  boolean hasNode();
  /**
   * <code>.pbanalysis.NodeMsg node = 1;</code>
   */
  io.yottachain.nodemgmt.analysis.pb.NodeMsg getNode();
  /**
   * <code>.pbanalysis.NodeMsg node = 1;</code>
   */
  io.yottachain.nodemgmt.analysis.pb.NodeMsgOrBuilder getNodeOrBuilder();

  /**
   * <code>repeated bytes shards = 2;</code>
   */
  java.util.List<com.google.protobuf.ByteString> getShardsList();
  /**
   * <code>repeated bytes shards = 2;</code>
   */
  int getShardsCount();
  /**
   * <code>repeated bytes shards = 2;</code>
   */
  com.google.protobuf.ByteString getShards(int index);
}
