// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

package io.yottachain.nodemgmt.analysis.pb;

public interface StringMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pbanalysis.StringMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string value = 1;</code>
   */
  java.lang.String getValue();
  /**
   * <code>string value = 1;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
