// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

package io.yottachain.nodemgmt.rebuilder.pb;

public interface DownloadShardRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb.DownloadShardRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes VHF = 1;</code>
   */
  com.google.protobuf.ByteString getVHF();
}
