// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

package io.yottachain.nodemgmt.rebuilder.pb;

public interface IncrUsedSpaceReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb.IncrUsedSpaceReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>int64 incr = 2;</code>
   */
  long getIncr();
}
