// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

package io.yottachain.nodemgmt.rebuilder.pb;

/**
 * <pre>
 *msgid=0x2cb0
 * </pre>
 *
 * Protobuf type {@code pb.MultiTaskDescription}
 */
public  final class MultiTaskDescription extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:pb.MultiTaskDescription)
    MultiTaskDescriptionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MultiTaskDescription.newBuilder() to construct.
  private MultiTaskDescription(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MultiTaskDescription() {
    tasklist_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MultiTaskDescription();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MultiTaskDescription(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              tasklist_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
              mutable_bitField0_ |= 0x00000001;
            }
            tasklist_.add(input.readBytes());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        tasklist_ = java.util.Collections.unmodifiableList(tasklist_); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.yottachain.nodemgmt.rebuilder.pb.RebuilderProto.internal_static_pb_MultiTaskDescription_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.yottachain.nodemgmt.rebuilder.pb.RebuilderProto.internal_static_pb_MultiTaskDescription_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.yottachain.nodemgmt.rebuilder.pb.MultiTaskDescription.class, io.yottachain.nodemgmt.rebuilder.pb.MultiTaskDescription.Builder.class);
  }

  public static final int TASKLIST_FIELD_NUMBER = 1;
  private java.util.List<com.google.protobuf.ByteString> tasklist_;
  /**
   * <code>repeated bytes tasklist = 1;</code>
   */
  public java.util.List<com.google.protobuf.ByteString>
      getTasklistList() {
    return tasklist_;
  }
  /**
   * <code>repeated bytes tasklist = 1;</code>
   */
  public int getTasklistCount() {
    return tasklist_.size();
  }
  /**
   * <code>repeated bytes tasklist = 1;</code>
   */
  public com.google.protobuf.ByteString getTasklist(int index) {
    return tasklist_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < tasklist_.size(); i++) {
      output.writeBytes(1, tasklist_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < tasklist_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeBytesSizeNoTag(tasklist_.get(i));
      }
      size += dataSize;
      size += 1 * getTasklistList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.yottachain.nodemgmt.rebuilder.pb.MultiTaskDescription)) {
      return super.equals(obj);
    }
    io.yottachain.nodemgmt.rebuilder.pb.MultiTaskDescription other = (io.yottachain.nodemgmt.rebuilder.pb.MultiTaskDescription) obj;

    if (!getTasklistList()
        .equals(other.getTasklistList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getTasklistCount() > 0) {
      hash = (37 * hash) + TASKLIST_FIELD_NUMBER;
      hash = (53 * hash) + getTasklistList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.yottachain.nodemgmt.rebuilder.pb.MultiTaskDescription parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.yottachain.nodemgmt.rebuilder.pb.MultiTaskDescription parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.yottachain.nodemgmt.rebuilder.pb.MultiTaskDescription parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.yottachain.nodemgmt.rebuilder.pb.MultiTaskDescription parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.yottachain.nodemgmt.rebuilder.pb.MultiTaskDescription parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.yottachain.nodemgmt.rebuilder.pb.MultiTaskDescription parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.yottachain.nodemgmt.rebuilder.pb.MultiTaskDescription parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.yottachain.nodemgmt.rebuilder.pb.MultiTaskDescription parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.yottachain.nodemgmt.rebuilder.pb.MultiTaskDescription parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.yottachain.nodemgmt.rebuilder.pb.MultiTaskDescription parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.yottachain.nodemgmt.rebuilder.pb.MultiTaskDescription parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.yottachain.nodemgmt.rebuilder.pb.MultiTaskDescription parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.yottachain.nodemgmt.rebuilder.pb.MultiTaskDescription prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *msgid=0x2cb0
   * </pre>
   *
   * Protobuf type {@code pb.MultiTaskDescription}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:pb.MultiTaskDescription)
      io.yottachain.nodemgmt.rebuilder.pb.MultiTaskDescriptionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.yottachain.nodemgmt.rebuilder.pb.RebuilderProto.internal_static_pb_MultiTaskDescription_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.yottachain.nodemgmt.rebuilder.pb.RebuilderProto.internal_static_pb_MultiTaskDescription_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.yottachain.nodemgmt.rebuilder.pb.MultiTaskDescription.class, io.yottachain.nodemgmt.rebuilder.pb.MultiTaskDescription.Builder.class);
    }

    // Construct using io.yottachain.nodemgmt.rebuilder.pb.MultiTaskDescription.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      tasklist_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.yottachain.nodemgmt.rebuilder.pb.RebuilderProto.internal_static_pb_MultiTaskDescription_descriptor;
    }

    @java.lang.Override
    public io.yottachain.nodemgmt.rebuilder.pb.MultiTaskDescription getDefaultInstanceForType() {
      return io.yottachain.nodemgmt.rebuilder.pb.MultiTaskDescription.getDefaultInstance();
    }

    @java.lang.Override
    public io.yottachain.nodemgmt.rebuilder.pb.MultiTaskDescription build() {
      io.yottachain.nodemgmt.rebuilder.pb.MultiTaskDescription result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.yottachain.nodemgmt.rebuilder.pb.MultiTaskDescription buildPartial() {
      io.yottachain.nodemgmt.rebuilder.pb.MultiTaskDescription result = new io.yottachain.nodemgmt.rebuilder.pb.MultiTaskDescription(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        tasklist_ = java.util.Collections.unmodifiableList(tasklist_);
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.tasklist_ = tasklist_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.yottachain.nodemgmt.rebuilder.pb.MultiTaskDescription) {
        return mergeFrom((io.yottachain.nodemgmt.rebuilder.pb.MultiTaskDescription)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.yottachain.nodemgmt.rebuilder.pb.MultiTaskDescription other) {
      if (other == io.yottachain.nodemgmt.rebuilder.pb.MultiTaskDescription.getDefaultInstance()) return this;
      if (!other.tasklist_.isEmpty()) {
        if (tasklist_.isEmpty()) {
          tasklist_ = other.tasklist_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureTasklistIsMutable();
          tasklist_.addAll(other.tasklist_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.yottachain.nodemgmt.rebuilder.pb.MultiTaskDescription parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.yottachain.nodemgmt.rebuilder.pb.MultiTaskDescription) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.google.protobuf.ByteString> tasklist_ = java.util.Collections.emptyList();
    private void ensureTasklistIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        tasklist_ = new java.util.ArrayList<com.google.protobuf.ByteString>(tasklist_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated bytes tasklist = 1;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getTasklistList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(tasklist_) : tasklist_;
    }
    /**
     * <code>repeated bytes tasklist = 1;</code>
     */
    public int getTasklistCount() {
      return tasklist_.size();
    }
    /**
     * <code>repeated bytes tasklist = 1;</code>
     */
    public com.google.protobuf.ByteString getTasklist(int index) {
      return tasklist_.get(index);
    }
    /**
     * <code>repeated bytes tasklist = 1;</code>
     */
    public Builder setTasklist(
        int index, com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureTasklistIsMutable();
      tasklist_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes tasklist = 1;</code>
     */
    public Builder addTasklist(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureTasklistIsMutable();
      tasklist_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes tasklist = 1;</code>
     */
    public Builder addAllTasklist(
        java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
      ensureTasklistIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, tasklist_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes tasklist = 1;</code>
     */
    public Builder clearTasklist() {
      tasklist_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:pb.MultiTaskDescription)
  }

  // @@protoc_insertion_point(class_scope:pb.MultiTaskDescription)
  private static final io.yottachain.nodemgmt.rebuilder.pb.MultiTaskDescription DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.yottachain.nodemgmt.rebuilder.pb.MultiTaskDescription();
  }

  public static io.yottachain.nodemgmt.rebuilder.pb.MultiTaskDescription getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MultiTaskDescription>
      PARSER = new com.google.protobuf.AbstractParser<MultiTaskDescription>() {
    @java.lang.Override
    public MultiTaskDescription parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MultiTaskDescription(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MultiTaskDescription> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MultiTaskDescription> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.yottachain.nodemgmt.rebuilder.pb.MultiTaskDescription getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

