// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

package io.yottachain.nodemgmt.rebuilder.pb;

public interface MultiTaskOpResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pbrebuilder.MultiTaskOpResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated bytes id = 1;</code>
   */
  java.util.List<com.google.protobuf.ByteString> getIdList();
  /**
   * <code>repeated bytes id = 1;</code>
   */
  int getIdCount();
  /**
   * <code>repeated bytes id = 1;</code>
   */
  com.google.protobuf.ByteString getId(int index);

  /**
   * <code>repeated int32 RES = 2;</code>
   */
  java.util.List<java.lang.Integer> getRESList();
  /**
   * <code>repeated int32 RES = 2;</code>
   */
  int getRESCount();
  /**
   * <code>repeated int32 RES = 2;</code>
   */
  int getRES(int index);
}
