// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

package io.yottachain.nodemgmt.rebuilder.pb;

public interface P2PLocationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb.P2PLocation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string nodeId = 1;</code>
   */
  java.lang.String getNodeId();
  /**
   * <code>string nodeId = 1;</code>
   */
  com.google.protobuf.ByteString
      getNodeIdBytes();

  /**
   * <code>repeated string addrs = 2;</code>
   */
  java.util.List<java.lang.String>
      getAddrsList();
  /**
   * <code>repeated string addrs = 2;</code>
   */
  int getAddrsCount();
  /**
   * <code>repeated string addrs = 2;</code>
   */
  java.lang.String getAddrs(int index);
  /**
   * <code>repeated string addrs = 2;</code>
   */
  com.google.protobuf.ByteString
      getAddrsBytes(int index);
}
