// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

package io.yottachain.nodemgmt.rebuilder.pb;

public interface SpotCheckListMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb.SpotCheckListMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string taskID = 1;</code>
   */
  java.lang.String getTaskID();
  /**
   * <code>string taskID = 1;</code>
   */
  com.google.protobuf.ByteString
      getTaskIDBytes();

  /**
   * <code>repeated .pb.SpotCheckTaskMsg taskList = 2;</code>
   */
  java.util.List<io.yottachain.nodemgmt.rebuilder.pb.SpotCheckTaskMsg> 
      getTaskListList();
  /**
   * <code>repeated .pb.SpotCheckTaskMsg taskList = 2;</code>
   */
  io.yottachain.nodemgmt.rebuilder.pb.SpotCheckTaskMsg getTaskList(int index);
  /**
   * <code>repeated .pb.SpotCheckTaskMsg taskList = 2;</code>
   */
  int getTaskListCount();
  /**
   * <code>repeated .pb.SpotCheckTaskMsg taskList = 2;</code>
   */
  java.util.List<? extends io.yottachain.nodemgmt.rebuilder.pb.SpotCheckTaskMsgOrBuilder> 
      getTaskListOrBuilderList();
  /**
   * <code>repeated .pb.SpotCheckTaskMsg taskList = 2;</code>
   */
  io.yottachain.nodemgmt.rebuilder.pb.SpotCheckTaskMsgOrBuilder getTaskListOrBuilder(
      int index);

  /**
   * <code>int64 timestamp = 3;</code>
   */
  long getTimestamp();
}
