// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

package io.yottachain.nodemgmt.rebuilder.pb;

public interface TaskDescriptionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pbrebuilder.TaskDescription)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes id = 1;</code>
   */
  com.google.protobuf.ByteString getId();

  /**
   * <code>repeated bytes hashs = 2;</code>
   */
  java.util.List<com.google.protobuf.ByteString> getHashsList();
  /**
   * <code>repeated bytes hashs = 2;</code>
   */
  int getHashsCount();
  /**
   * <code>repeated bytes hashs = 2;</code>
   */
  com.google.protobuf.ByteString getHashs(int index);

  /**
   * <code>repeated .pbrebuilder.P2PLocation locations = 3;</code>
   */
  java.util.List<io.yottachain.nodemgmt.rebuilder.pb.P2PLocation> 
      getLocationsList();
  /**
   * <code>repeated .pbrebuilder.P2PLocation locations = 3;</code>
   */
  io.yottachain.nodemgmt.rebuilder.pb.P2PLocation getLocations(int index);
  /**
   * <code>repeated .pbrebuilder.P2PLocation locations = 3;</code>
   */
  int getLocationsCount();
  /**
   * <code>repeated .pbrebuilder.P2PLocation locations = 3;</code>
   */
  java.util.List<? extends io.yottachain.nodemgmt.rebuilder.pb.P2PLocationOrBuilder> 
      getLocationsOrBuilderList();
  /**
   * <code>repeated .pbrebuilder.P2PLocation locations = 3;</code>
   */
  io.yottachain.nodemgmt.rebuilder.pb.P2PLocationOrBuilder getLocationsOrBuilder(
      int index);

  /**
   * <code>int32 parityShardCount = 4;</code>
   */
  int getParityShardCount();

  /**
   * <code>int32 recoverId = 5;</code>
   */
  int getRecoverId();
}
