// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

package io.yottachain.nodemgmt.rebuilder.pb;

public interface TaskOpResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pbrebuilder.TaskOpResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes id = 1;</code>
   */
  com.google.protobuf.ByteString getId();

  /**
   * <code>int32 RES = 2;</code>
   */
  int getRES();
}
