// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

package io.yottachain.nodemgmt.rebuilder.pb;

public interface UpdateUspaceMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb.UpdateUspaceMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 nodeID = 1;</code>
   */
  int getNodeID();

  /**
   * <code>int32 fromNodeID = 2;</code>
   */
  int getFromNodeID();

  /**
   * <code>int64 uspace = 3;</code>
   */
  long getUspace();
}
