// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

package io.yottachain.nodemgmt.rebuilder.pb;

/**
 * Protobuf type {@code pb.UpdateUspaceMessage}
 */
public  final class UpdateUspaceMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:pb.UpdateUspaceMessage)
    UpdateUspaceMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UpdateUspaceMessage.newBuilder() to construct.
  private UpdateUspaceMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UpdateUspaceMessage() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UpdateUspaceMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UpdateUspaceMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            nodeID_ = input.readInt32();
            break;
          }
          case 16: {

            fromNodeID_ = input.readInt32();
            break;
          }
          case 24: {

            uspace_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.yottachain.nodemgmt.rebuilder.pb.RebuilderProto.internal_static_pb_UpdateUspaceMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.yottachain.nodemgmt.rebuilder.pb.RebuilderProto.internal_static_pb_UpdateUspaceMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.yottachain.nodemgmt.rebuilder.pb.UpdateUspaceMessage.class, io.yottachain.nodemgmt.rebuilder.pb.UpdateUspaceMessage.Builder.class);
  }

  public static final int NODEID_FIELD_NUMBER = 1;
  private int nodeID_;
  /**
   * <code>int32 nodeID = 1;</code>
   */
  public int getNodeID() {
    return nodeID_;
  }

  public static final int FROMNODEID_FIELD_NUMBER = 2;
  private int fromNodeID_;
  /**
   * <code>int32 fromNodeID = 2;</code>
   */
  public int getFromNodeID() {
    return fromNodeID_;
  }

  public static final int USPACE_FIELD_NUMBER = 3;
  private long uspace_;
  /**
   * <code>int64 uspace = 3;</code>
   */
  public long getUspace() {
    return uspace_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (nodeID_ != 0) {
      output.writeInt32(1, nodeID_);
    }
    if (fromNodeID_ != 0) {
      output.writeInt32(2, fromNodeID_);
    }
    if (uspace_ != 0L) {
      output.writeInt64(3, uspace_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (nodeID_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, nodeID_);
    }
    if (fromNodeID_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, fromNodeID_);
    }
    if (uspace_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, uspace_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.yottachain.nodemgmt.rebuilder.pb.UpdateUspaceMessage)) {
      return super.equals(obj);
    }
    io.yottachain.nodemgmt.rebuilder.pb.UpdateUspaceMessage other = (io.yottachain.nodemgmt.rebuilder.pb.UpdateUspaceMessage) obj;

    if (getNodeID()
        != other.getNodeID()) return false;
    if (getFromNodeID()
        != other.getFromNodeID()) return false;
    if (getUspace()
        != other.getUspace()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NODEID_FIELD_NUMBER;
    hash = (53 * hash) + getNodeID();
    hash = (37 * hash) + FROMNODEID_FIELD_NUMBER;
    hash = (53 * hash) + getFromNodeID();
    hash = (37 * hash) + USPACE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUspace());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.yottachain.nodemgmt.rebuilder.pb.UpdateUspaceMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.yottachain.nodemgmt.rebuilder.pb.UpdateUspaceMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.yottachain.nodemgmt.rebuilder.pb.UpdateUspaceMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.yottachain.nodemgmt.rebuilder.pb.UpdateUspaceMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.yottachain.nodemgmt.rebuilder.pb.UpdateUspaceMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.yottachain.nodemgmt.rebuilder.pb.UpdateUspaceMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.yottachain.nodemgmt.rebuilder.pb.UpdateUspaceMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.yottachain.nodemgmt.rebuilder.pb.UpdateUspaceMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.yottachain.nodemgmt.rebuilder.pb.UpdateUspaceMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.yottachain.nodemgmt.rebuilder.pb.UpdateUspaceMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.yottachain.nodemgmt.rebuilder.pb.UpdateUspaceMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.yottachain.nodemgmt.rebuilder.pb.UpdateUspaceMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.yottachain.nodemgmt.rebuilder.pb.UpdateUspaceMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code pb.UpdateUspaceMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:pb.UpdateUspaceMessage)
      io.yottachain.nodemgmt.rebuilder.pb.UpdateUspaceMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.yottachain.nodemgmt.rebuilder.pb.RebuilderProto.internal_static_pb_UpdateUspaceMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.yottachain.nodemgmt.rebuilder.pb.RebuilderProto.internal_static_pb_UpdateUspaceMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.yottachain.nodemgmt.rebuilder.pb.UpdateUspaceMessage.class, io.yottachain.nodemgmt.rebuilder.pb.UpdateUspaceMessage.Builder.class);
    }

    // Construct using io.yottachain.nodemgmt.rebuilder.pb.UpdateUspaceMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      nodeID_ = 0;

      fromNodeID_ = 0;

      uspace_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.yottachain.nodemgmt.rebuilder.pb.RebuilderProto.internal_static_pb_UpdateUspaceMessage_descriptor;
    }

    @java.lang.Override
    public io.yottachain.nodemgmt.rebuilder.pb.UpdateUspaceMessage getDefaultInstanceForType() {
      return io.yottachain.nodemgmt.rebuilder.pb.UpdateUspaceMessage.getDefaultInstance();
    }

    @java.lang.Override
    public io.yottachain.nodemgmt.rebuilder.pb.UpdateUspaceMessage build() {
      io.yottachain.nodemgmt.rebuilder.pb.UpdateUspaceMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.yottachain.nodemgmt.rebuilder.pb.UpdateUspaceMessage buildPartial() {
      io.yottachain.nodemgmt.rebuilder.pb.UpdateUspaceMessage result = new io.yottachain.nodemgmt.rebuilder.pb.UpdateUspaceMessage(this);
      result.nodeID_ = nodeID_;
      result.fromNodeID_ = fromNodeID_;
      result.uspace_ = uspace_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.yottachain.nodemgmt.rebuilder.pb.UpdateUspaceMessage) {
        return mergeFrom((io.yottachain.nodemgmt.rebuilder.pb.UpdateUspaceMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.yottachain.nodemgmt.rebuilder.pb.UpdateUspaceMessage other) {
      if (other == io.yottachain.nodemgmt.rebuilder.pb.UpdateUspaceMessage.getDefaultInstance()) return this;
      if (other.getNodeID() != 0) {
        setNodeID(other.getNodeID());
      }
      if (other.getFromNodeID() != 0) {
        setFromNodeID(other.getFromNodeID());
      }
      if (other.getUspace() != 0L) {
        setUspace(other.getUspace());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.yottachain.nodemgmt.rebuilder.pb.UpdateUspaceMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.yottachain.nodemgmt.rebuilder.pb.UpdateUspaceMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int nodeID_ ;
    /**
     * <code>int32 nodeID = 1;</code>
     */
    public int getNodeID() {
      return nodeID_;
    }
    /**
     * <code>int32 nodeID = 1;</code>
     */
    public Builder setNodeID(int value) {
      
      nodeID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 nodeID = 1;</code>
     */
    public Builder clearNodeID() {
      
      nodeID_ = 0;
      onChanged();
      return this;
    }

    private int fromNodeID_ ;
    /**
     * <code>int32 fromNodeID = 2;</code>
     */
    public int getFromNodeID() {
      return fromNodeID_;
    }
    /**
     * <code>int32 fromNodeID = 2;</code>
     */
    public Builder setFromNodeID(int value) {
      
      fromNodeID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 fromNodeID = 2;</code>
     */
    public Builder clearFromNodeID() {
      
      fromNodeID_ = 0;
      onChanged();
      return this;
    }

    private long uspace_ ;
    /**
     * <code>int64 uspace = 3;</code>
     */
    public long getUspace() {
      return uspace_;
    }
    /**
     * <code>int64 uspace = 3;</code>
     */
    public Builder setUspace(long value) {
      
      uspace_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 uspace = 3;</code>
     */
    public Builder clearUspace() {
      
      uspace_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:pb.UpdateUspaceMessage)
  }

  // @@protoc_insertion_point(class_scope:pb.UpdateUspaceMessage)
  private static final io.yottachain.nodemgmt.rebuilder.pb.UpdateUspaceMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.yottachain.nodemgmt.rebuilder.pb.UpdateUspaceMessage();
  }

  public static io.yottachain.nodemgmt.rebuilder.pb.UpdateUspaceMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UpdateUspaceMessage>
      PARSER = new com.google.protobuf.AbstractParser<UpdateUspaceMessage>() {
    @java.lang.Override
    public UpdateUspaceMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UpdateUspaceMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UpdateUspaceMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UpdateUspaceMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.yottachain.nodemgmt.rebuilder.pb.UpdateUspaceMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

