// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

package io.yottachain.nodemgmt.pb;

/**
 * <pre>
 * Node message
 * </pre>
 *
 * Protobuf type {@code pb.NodeMsg}
 */
public  final class NodeMsg extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:pb.NodeMsg)
    NodeMsgOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NodeMsg.newBuilder() to construct.
  private NodeMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NodeMsg() {
    nodeID_ = "";
    pubKey_ = "";
    owner_ = "";
    profitAcc_ = "";
    poolID_ = "";
    poolOwner_ = "";
    addrs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    ext_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new NodeMsg();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private NodeMsg(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            iD_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            nodeID_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            pubKey_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            owner_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            profitAcc_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            poolID_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            poolOwner_ = s;
            break;
          }
          case 64: {

            quota_ = input.readInt64();
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              addrs_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            addrs_.add(s);
            break;
          }
          case 80: {

            cPU_ = input.readInt32();
            break;
          }
          case 88: {

            memory_ = input.readInt32();
            break;
          }
          case 96: {

            bandwidth_ = input.readInt32();
            break;
          }
          case 104: {

            maxDataSpace_ = input.readInt64();
            break;
          }
          case 112: {

            assignedSpace_ = input.readInt64();
            break;
          }
          case 120: {

            productiveSpace_ = input.readInt64();
            break;
          }
          case 128: {

            usedSpace_ = input.readInt64();
            break;
          }
          case 137: {

            weight_ = input.readDouble();
            break;
          }
          case 144: {

            valid_ = input.readInt32();
            break;
          }
          case 152: {

            relay_ = input.readInt32();
            break;
          }
          case 160: {

            status_ = input.readInt32();
            break;
          }
          case 168: {

            timestamp_ = input.readInt64();
            break;
          }
          case 176: {

            version_ = input.readInt32();
            break;
          }
          case 184: {

            rebuilding_ = input.readInt32();
            break;
          }
          case 192: {

            realSpace_ = input.readInt64();
            break;
          }
          case 200: {

            tx_ = input.readInt64();
            break;
          }
          case 208: {

            rx_ = input.readInt64();
            break;
          }
          case 218: {
            java.lang.String s = input.readStringRequireUtf8();

            ext_ = s;
            break;
          }
          case 226: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              uspaces_ = com.google.protobuf.MapField.newMapField(
                  UspacesDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000002;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.Long>
            uspaces__ = input.readMessage(
                UspacesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            uspaces_.getMutableMap().put(
                uspaces__.getKey(), uspaces__.getValue());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        addrs_ = addrs_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.yottachain.nodemgmt.pb.NodeMgmtProto.internal_static_pb_NodeMsg_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 28:
        return internalGetUspaces();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.yottachain.nodemgmt.pb.NodeMgmtProto.internal_static_pb_NodeMsg_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.yottachain.nodemgmt.pb.NodeMsg.class, io.yottachain.nodemgmt.pb.NodeMsg.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private int iD_;
  /**
   * <pre>
   *data node index
   * </pre>
   *
   * <code>int32 iD = 1;</code>
   */
  public int getID() {
    return iD_;
  }

  public static final int NODEID_FIELD_NUMBER = 2;
  private volatile java.lang.Object nodeID_;
  /**
   * <pre>
   *data node ID, generated from PubKey
   * </pre>
   *
   * <code>string nodeID = 2;</code>
   */
  public java.lang.String getNodeID() {
    java.lang.Object ref = nodeID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nodeID_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *data node ID, generated from PubKey
   * </pre>
   *
   * <code>string nodeID = 2;</code>
   */
  public com.google.protobuf.ByteString
      getNodeIDBytes() {
    java.lang.Object ref = nodeID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nodeID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PUBKEY_FIELD_NUMBER = 3;
  private volatile java.lang.Object pubKey_;
  /**
   * <pre>
   *public key of data node
   * </pre>
   *
   * <code>string pubKey = 3;</code>
   */
  public java.lang.String getPubKey() {
    java.lang.Object ref = pubKey_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pubKey_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *public key of data node
   * </pre>
   *
   * <code>string pubKey = 3;</code>
   */
  public com.google.protobuf.ByteString
      getPubKeyBytes() {
    java.lang.Object ref = pubKey_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pubKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OWNER_FIELD_NUMBER = 4;
  private volatile java.lang.Object owner_;
  /**
   * <pre>
   *owner account of this miner
   * </pre>
   *
   * <code>string owner = 4;</code>
   */
  public java.lang.String getOwner() {
    java.lang.Object ref = owner_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      owner_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *owner account of this miner
   * </pre>
   *
   * <code>string owner = 4;</code>
   */
  public com.google.protobuf.ByteString
      getOwnerBytes() {
    java.lang.Object ref = owner_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      owner_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROFITACC_FIELD_NUMBER = 5;
  private volatile java.lang.Object profitAcc_;
  /**
   * <pre>
   *profit account of this miner
   * </pre>
   *
   * <code>string profitAcc = 5;</code>
   */
  public java.lang.String getProfitAcc() {
    java.lang.Object ref = profitAcc_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      profitAcc_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *profit account of this miner
   * </pre>
   *
   * <code>string profitAcc = 5;</code>
   */
  public com.google.protobuf.ByteString
      getProfitAccBytes() {
    java.lang.Object ref = profitAcc_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      profitAcc_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int POOLID_FIELD_NUMBER = 6;
  private volatile java.lang.Object poolID_;
  /**
   * <pre>
   *ID of associated miner pool
   * </pre>
   *
   * <code>string poolID = 6;</code>
   */
  public java.lang.String getPoolID() {
    java.lang.Object ref = poolID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      poolID_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *ID of associated miner pool
   * </pre>
   *
   * <code>string poolID = 6;</code>
   */
  public com.google.protobuf.ByteString
      getPoolIDBytes() {
    java.lang.Object ref = poolID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      poolID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int POOLOWNER_FIELD_NUMBER = 7;
  private volatile java.lang.Object poolOwner_;
  /**
   * <pre>
   *Owner of associated miner pool
   * </pre>
   *
   * <code>string poolOwner = 7;</code>
   */
  public java.lang.String getPoolOwner() {
    java.lang.Object ref = poolOwner_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      poolOwner_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *Owner of associated miner pool
   * </pre>
   *
   * <code>string poolOwner = 7;</code>
   */
  public com.google.protobuf.ByteString
      getPoolOwnerBytes() {
    java.lang.Object ref = poolOwner_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      poolOwner_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QUOTA_FIELD_NUMBER = 8;
  private long quota_;
  /**
   * <pre>
   *quota allocated by associated miner pool
   * </pre>
   *
   * <code>int64 quota = 8;</code>
   */
  public long getQuota() {
    return quota_;
  }

  public static final int ADDRS_FIELD_NUMBER = 9;
  private com.google.protobuf.LazyStringList addrs_;
  /**
   * <pre>
   *listening addresses of data node
   * </pre>
   *
   * <code>repeated string addrs = 9;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getAddrsList() {
    return addrs_;
  }
  /**
   * <pre>
   *listening addresses of data node
   * </pre>
   *
   * <code>repeated string addrs = 9;</code>
   */
  public int getAddrsCount() {
    return addrs_.size();
  }
  /**
   * <pre>
   *listening addresses of data node
   * </pre>
   *
   * <code>repeated string addrs = 9;</code>
   */
  public java.lang.String getAddrs(int index) {
    return addrs_.get(index);
  }
  /**
   * <pre>
   *listening addresses of data node
   * </pre>
   *
   * <code>repeated string addrs = 9;</code>
   */
  public com.google.protobuf.ByteString
      getAddrsBytes(int index) {
    return addrs_.getByteString(index);
  }

  public static final int CPU_FIELD_NUMBER = 10;
  private int cPU_;
  /**
   * <pre>
   *CPU usage of data node
   * </pre>
   *
   * <code>int32 cPU = 10;</code>
   */
  public int getCPU() {
    return cPU_;
  }

  public static final int MEMORY_FIELD_NUMBER = 11;
  private int memory_;
  /**
   * <pre>
   *memory usage of data node
   * </pre>
   *
   * <code>int32 memory = 11;</code>
   */
  public int getMemory() {
    return memory_;
  }

  public static final int BANDWIDTH_FIELD_NUMBER = 12;
  private int bandwidth_;
  /**
   * <pre>
   *bandwidth usage of data node
   * </pre>
   *
   * <code>int32 bandwidth = 12;</code>
   */
  public int getBandwidth() {
    return bandwidth_;
  }

  public static final int MAXDATASPACE_FIELD_NUMBER = 13;
  private long maxDataSpace_;
  /**
   * <pre>
   *max space of data node
   * </pre>
   *
   * <code>int64 maxDataSpace = 13;</code>
   */
  public long getMaxDataSpace() {
    return maxDataSpace_;
  }

  public static final int ASSIGNEDSPACE_FIELD_NUMBER = 14;
  private long assignedSpace_;
  /**
   * <pre>
   *space assigned to YTFS
   * </pre>
   *
   * <code>int64 assignedSpace = 14;</code>
   */
  public long getAssignedSpace() {
    return assignedSpace_;
  }

  public static final int PRODUCTIVESPACE_FIELD_NUMBER = 15;
  private long productiveSpace_;
  /**
   * <pre>
   *pre-allocated space of data node
   * </pre>
   *
   * <code>int64 productiveSpace = 15;</code>
   */
  public long getProductiveSpace() {
    return productiveSpace_;
  }

  public static final int USEDSPACE_FIELD_NUMBER = 16;
  private long usedSpace_;
  /**
   * <pre>
   *used space of data node
   * </pre>
   *
   * <code>int64 usedSpace = 16;</code>
   */
  public long getUsedSpace() {
    return usedSpace_;
  }

  public static final int WEIGHT_FIELD_NUMBER = 17;
  private double weight_;
  /**
   * <pre>
   *weight for allocate data node
   * </pre>
   *
   * <code>double weight = 17;</code>
   */
  public double getWeight() {
    return weight_;
  }

  public static final int VALID_FIELD_NUMBER = 18;
  private int valid_;
  /**
   * <pre>
   *Is node valid
   * </pre>
   *
   * <code>int32 valid = 18;</code>
   */
  public int getValid() {
    return valid_;
  }

  public static final int RELAY_FIELD_NUMBER = 19;
  private int relay_;
  /**
   * <pre>
   *Is relay node
   * </pre>
   *
   * <code>int32 relay = 19;</code>
   */
  public int getRelay() {
    return relay_;
  }

  public static final int STATUS_FIELD_NUMBER = 20;
  private int status_;
  /**
   * <pre>
   *status code: 0 - registered 1 - active
   * </pre>
   *
   * <code>int32 status = 20;</code>
   */
  public int getStatus() {
    return status_;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 21;
  private long timestamp_;
  /**
   * <pre>
   *timestamp of status updating operation
   * </pre>
   *
   * <code>int64 timestamp = 21;</code>
   */
  public long getTimestamp() {
    return timestamp_;
  }

  public static final int VERSION_FIELD_NUMBER = 22;
  private int version_;
  /**
   * <pre>
   *version number of miner
   * </pre>
   *
   * <code>int32 version = 22;</code>
   */
  public int getVersion() {
    return version_;
  }

  public static final int REBUILDING_FIELD_NUMBER = 23;
  private int rebuilding_;
  /**
   * <pre>
   *if node is under rebuilding
   * </pre>
   *
   * <code>int32 rebuilding = 23;</code>
   */
  public int getRebuilding() {
    return rebuilding_;
  }

  public static final int REALSPACE_FIELD_NUMBER = 24;
  private long realSpace_;
  /**
   * <pre>
   *real space of miner
   * </pre>
   *
   * <code>int64 realSpace = 24;</code>
   */
  public long getRealSpace() {
    return realSpace_;
  }

  public static final int TX_FIELD_NUMBER = 25;
  private long tx_;
  /**
   * <pre>
   *tx
   * </pre>
   *
   * <code>int64 tx = 25;</code>
   */
  public long getTx() {
    return tx_;
  }

  public static final int RX_FIELD_NUMBER = 26;
  private long rx_;
  /**
   * <pre>
   *rx
   * </pre>
   *
   * <code>int64 rx = 26;</code>
   */
  public long getRx() {
    return rx_;
  }

  public static final int EXT_FIELD_NUMBER = 27;
  private volatile java.lang.Object ext_;
  /**
   * <pre>
   *other
   * </pre>
   *
   * <code>string ext = 27;</code>
   */
  public java.lang.String getExt() {
    java.lang.Object ref = ext_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ext_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *other
   * </pre>
   *
   * <code>string ext = 27;</code>
   */
  public com.google.protobuf.ByteString
      getExtBytes() {
    java.lang.Object ref = ext_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ext_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USPACES_FIELD_NUMBER = 28;
  private static final class UspacesDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.Long> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.Long>newDefaultInstance(
                io.yottachain.nodemgmt.pb.NodeMgmtProto.internal_static_pb_NodeMsg_UspacesEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.INT64,
                0L);
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.Long> uspaces_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.Long>
  internalGetUspaces() {
    if (uspaces_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          UspacesDefaultEntryHolder.defaultEntry);
    }
    return uspaces_;
  }

  public int getUspacesCount() {
    return internalGetUspaces().getMap().size();
  }
  /**
   * <pre>
   *used spaces on each SN
   * </pre>
   *
   * <code>map&lt;string, int64&gt; uspaces = 28;</code>
   */

  public boolean containsUspaces(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetUspaces().getMap().containsKey(key);
  }
  /**
   * Use {@link #getUspacesMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.Long> getUspaces() {
    return getUspacesMap();
  }
  /**
   * <pre>
   *used spaces on each SN
   * </pre>
   *
   * <code>map&lt;string, int64&gt; uspaces = 28;</code>
   */

  public java.util.Map<java.lang.String, java.lang.Long> getUspacesMap() {
    return internalGetUspaces().getMap();
  }
  /**
   * <pre>
   *used spaces on each SN
   * </pre>
   *
   * <code>map&lt;string, int64&gt; uspaces = 28;</code>
   */

  public long getUspacesOrDefault(
      java.lang.String key,
      long defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.Long> map =
        internalGetUspaces().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   *used spaces on each SN
   * </pre>
   *
   * <code>map&lt;string, int64&gt; uspaces = 28;</code>
   */

  public long getUspacesOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.Long> map =
        internalGetUspaces().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (iD_ != 0) {
      output.writeInt32(1, iD_);
    }
    if (!getNodeIDBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, nodeID_);
    }
    if (!getPubKeyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, pubKey_);
    }
    if (!getOwnerBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, owner_);
    }
    if (!getProfitAccBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, profitAcc_);
    }
    if (!getPoolIDBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, poolID_);
    }
    if (!getPoolOwnerBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, poolOwner_);
    }
    if (quota_ != 0L) {
      output.writeInt64(8, quota_);
    }
    for (int i = 0; i < addrs_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, addrs_.getRaw(i));
    }
    if (cPU_ != 0) {
      output.writeInt32(10, cPU_);
    }
    if (memory_ != 0) {
      output.writeInt32(11, memory_);
    }
    if (bandwidth_ != 0) {
      output.writeInt32(12, bandwidth_);
    }
    if (maxDataSpace_ != 0L) {
      output.writeInt64(13, maxDataSpace_);
    }
    if (assignedSpace_ != 0L) {
      output.writeInt64(14, assignedSpace_);
    }
    if (productiveSpace_ != 0L) {
      output.writeInt64(15, productiveSpace_);
    }
    if (usedSpace_ != 0L) {
      output.writeInt64(16, usedSpace_);
    }
    if (weight_ != 0D) {
      output.writeDouble(17, weight_);
    }
    if (valid_ != 0) {
      output.writeInt32(18, valid_);
    }
    if (relay_ != 0) {
      output.writeInt32(19, relay_);
    }
    if (status_ != 0) {
      output.writeInt32(20, status_);
    }
    if (timestamp_ != 0L) {
      output.writeInt64(21, timestamp_);
    }
    if (version_ != 0) {
      output.writeInt32(22, version_);
    }
    if (rebuilding_ != 0) {
      output.writeInt32(23, rebuilding_);
    }
    if (realSpace_ != 0L) {
      output.writeInt64(24, realSpace_);
    }
    if (tx_ != 0L) {
      output.writeInt64(25, tx_);
    }
    if (rx_ != 0L) {
      output.writeInt64(26, rx_);
    }
    if (!getExtBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 27, ext_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetUspaces(),
        UspacesDefaultEntryHolder.defaultEntry,
        28);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (iD_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, iD_);
    }
    if (!getNodeIDBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, nodeID_);
    }
    if (!getPubKeyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, pubKey_);
    }
    if (!getOwnerBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, owner_);
    }
    if (!getProfitAccBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, profitAcc_);
    }
    if (!getPoolIDBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, poolID_);
    }
    if (!getPoolOwnerBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, poolOwner_);
    }
    if (quota_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(8, quota_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < addrs_.size(); i++) {
        dataSize += computeStringSizeNoTag(addrs_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getAddrsList().size();
    }
    if (cPU_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(10, cPU_);
    }
    if (memory_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(11, memory_);
    }
    if (bandwidth_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(12, bandwidth_);
    }
    if (maxDataSpace_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(13, maxDataSpace_);
    }
    if (assignedSpace_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(14, assignedSpace_);
    }
    if (productiveSpace_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(15, productiveSpace_);
    }
    if (usedSpace_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(16, usedSpace_);
    }
    if (weight_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(17, weight_);
    }
    if (valid_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(18, valid_);
    }
    if (relay_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(19, relay_);
    }
    if (status_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(20, status_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(21, timestamp_);
    }
    if (version_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(22, version_);
    }
    if (rebuilding_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(23, rebuilding_);
    }
    if (realSpace_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(24, realSpace_);
    }
    if (tx_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(25, tx_);
    }
    if (rx_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(26, rx_);
    }
    if (!getExtBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(27, ext_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.Long> entry
         : internalGetUspaces().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.Long>
      uspaces__ = UspacesDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(28, uspaces__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.yottachain.nodemgmt.pb.NodeMsg)) {
      return super.equals(obj);
    }
    io.yottachain.nodemgmt.pb.NodeMsg other = (io.yottachain.nodemgmt.pb.NodeMsg) obj;

    if (getID()
        != other.getID()) return false;
    if (!getNodeID()
        .equals(other.getNodeID())) return false;
    if (!getPubKey()
        .equals(other.getPubKey())) return false;
    if (!getOwner()
        .equals(other.getOwner())) return false;
    if (!getProfitAcc()
        .equals(other.getProfitAcc())) return false;
    if (!getPoolID()
        .equals(other.getPoolID())) return false;
    if (!getPoolOwner()
        .equals(other.getPoolOwner())) return false;
    if (getQuota()
        != other.getQuota()) return false;
    if (!getAddrsList()
        .equals(other.getAddrsList())) return false;
    if (getCPU()
        != other.getCPU()) return false;
    if (getMemory()
        != other.getMemory()) return false;
    if (getBandwidth()
        != other.getBandwidth()) return false;
    if (getMaxDataSpace()
        != other.getMaxDataSpace()) return false;
    if (getAssignedSpace()
        != other.getAssignedSpace()) return false;
    if (getProductiveSpace()
        != other.getProductiveSpace()) return false;
    if (getUsedSpace()
        != other.getUsedSpace()) return false;
    if (java.lang.Double.doubleToLongBits(getWeight())
        != java.lang.Double.doubleToLongBits(
            other.getWeight())) return false;
    if (getValid()
        != other.getValid()) return false;
    if (getRelay()
        != other.getRelay()) return false;
    if (getStatus()
        != other.getStatus()) return false;
    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (getVersion()
        != other.getVersion()) return false;
    if (getRebuilding()
        != other.getRebuilding()) return false;
    if (getRealSpace()
        != other.getRealSpace()) return false;
    if (getTx()
        != other.getTx()) return false;
    if (getRx()
        != other.getRx()) return false;
    if (!getExt()
        .equals(other.getExt())) return false;
    if (!internalGetUspaces().equals(
        other.internalGetUspaces())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getID();
    hash = (37 * hash) + NODEID_FIELD_NUMBER;
    hash = (53 * hash) + getNodeID().hashCode();
    hash = (37 * hash) + PUBKEY_FIELD_NUMBER;
    hash = (53 * hash) + getPubKey().hashCode();
    hash = (37 * hash) + OWNER_FIELD_NUMBER;
    hash = (53 * hash) + getOwner().hashCode();
    hash = (37 * hash) + PROFITACC_FIELD_NUMBER;
    hash = (53 * hash) + getProfitAcc().hashCode();
    hash = (37 * hash) + POOLID_FIELD_NUMBER;
    hash = (53 * hash) + getPoolID().hashCode();
    hash = (37 * hash) + POOLOWNER_FIELD_NUMBER;
    hash = (53 * hash) + getPoolOwner().hashCode();
    hash = (37 * hash) + QUOTA_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getQuota());
    if (getAddrsCount() > 0) {
      hash = (37 * hash) + ADDRS_FIELD_NUMBER;
      hash = (53 * hash) + getAddrsList().hashCode();
    }
    hash = (37 * hash) + CPU_FIELD_NUMBER;
    hash = (53 * hash) + getCPU();
    hash = (37 * hash) + MEMORY_FIELD_NUMBER;
    hash = (53 * hash) + getMemory();
    hash = (37 * hash) + BANDWIDTH_FIELD_NUMBER;
    hash = (53 * hash) + getBandwidth();
    hash = (37 * hash) + MAXDATASPACE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMaxDataSpace());
    hash = (37 * hash) + ASSIGNEDSPACE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAssignedSpace());
    hash = (37 * hash) + PRODUCTIVESPACE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getProductiveSpace());
    hash = (37 * hash) + USEDSPACE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUsedSpace());
    hash = (37 * hash) + WEIGHT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getWeight()));
    hash = (37 * hash) + VALID_FIELD_NUMBER;
    hash = (53 * hash) + getValid();
    hash = (37 * hash) + RELAY_FIELD_NUMBER;
    hash = (53 * hash) + getRelay();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion();
    hash = (37 * hash) + REBUILDING_FIELD_NUMBER;
    hash = (53 * hash) + getRebuilding();
    hash = (37 * hash) + REALSPACE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getRealSpace());
    hash = (37 * hash) + TX_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTx());
    hash = (37 * hash) + RX_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getRx());
    hash = (37 * hash) + EXT_FIELD_NUMBER;
    hash = (53 * hash) + getExt().hashCode();
    if (!internalGetUspaces().getMap().isEmpty()) {
      hash = (37 * hash) + USPACES_FIELD_NUMBER;
      hash = (53 * hash) + internalGetUspaces().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.yottachain.nodemgmt.pb.NodeMsg parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.yottachain.nodemgmt.pb.NodeMsg parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.yottachain.nodemgmt.pb.NodeMsg parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.yottachain.nodemgmt.pb.NodeMsg parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.yottachain.nodemgmt.pb.NodeMsg parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.yottachain.nodemgmt.pb.NodeMsg parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.yottachain.nodemgmt.pb.NodeMsg parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.yottachain.nodemgmt.pb.NodeMsg parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.yottachain.nodemgmt.pb.NodeMsg parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.yottachain.nodemgmt.pb.NodeMsg parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.yottachain.nodemgmt.pb.NodeMsg parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.yottachain.nodemgmt.pb.NodeMsg parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.yottachain.nodemgmt.pb.NodeMsg prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Node message
   * </pre>
   *
   * Protobuf type {@code pb.NodeMsg}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:pb.NodeMsg)
      io.yottachain.nodemgmt.pb.NodeMsgOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.yottachain.nodemgmt.pb.NodeMgmtProto.internal_static_pb_NodeMsg_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 28:
          return internalGetUspaces();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 28:
          return internalGetMutableUspaces();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.yottachain.nodemgmt.pb.NodeMgmtProto.internal_static_pb_NodeMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.yottachain.nodemgmt.pb.NodeMsg.class, io.yottachain.nodemgmt.pb.NodeMsg.Builder.class);
    }

    // Construct using io.yottachain.nodemgmt.pb.NodeMsg.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      iD_ = 0;

      nodeID_ = "";

      pubKey_ = "";

      owner_ = "";

      profitAcc_ = "";

      poolID_ = "";

      poolOwner_ = "";

      quota_ = 0L;

      addrs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      cPU_ = 0;

      memory_ = 0;

      bandwidth_ = 0;

      maxDataSpace_ = 0L;

      assignedSpace_ = 0L;

      productiveSpace_ = 0L;

      usedSpace_ = 0L;

      weight_ = 0D;

      valid_ = 0;

      relay_ = 0;

      status_ = 0;

      timestamp_ = 0L;

      version_ = 0;

      rebuilding_ = 0;

      realSpace_ = 0L;

      tx_ = 0L;

      rx_ = 0L;

      ext_ = "";

      internalGetMutableUspaces().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.yottachain.nodemgmt.pb.NodeMgmtProto.internal_static_pb_NodeMsg_descriptor;
    }

    @java.lang.Override
    public io.yottachain.nodemgmt.pb.NodeMsg getDefaultInstanceForType() {
      return io.yottachain.nodemgmt.pb.NodeMsg.getDefaultInstance();
    }

    @java.lang.Override
    public io.yottachain.nodemgmt.pb.NodeMsg build() {
      io.yottachain.nodemgmt.pb.NodeMsg result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.yottachain.nodemgmt.pb.NodeMsg buildPartial() {
      io.yottachain.nodemgmt.pb.NodeMsg result = new io.yottachain.nodemgmt.pb.NodeMsg(this);
      int from_bitField0_ = bitField0_;
      result.iD_ = iD_;
      result.nodeID_ = nodeID_;
      result.pubKey_ = pubKey_;
      result.owner_ = owner_;
      result.profitAcc_ = profitAcc_;
      result.poolID_ = poolID_;
      result.poolOwner_ = poolOwner_;
      result.quota_ = quota_;
      if (((bitField0_ & 0x00000001) != 0)) {
        addrs_ = addrs_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.addrs_ = addrs_;
      result.cPU_ = cPU_;
      result.memory_ = memory_;
      result.bandwidth_ = bandwidth_;
      result.maxDataSpace_ = maxDataSpace_;
      result.assignedSpace_ = assignedSpace_;
      result.productiveSpace_ = productiveSpace_;
      result.usedSpace_ = usedSpace_;
      result.weight_ = weight_;
      result.valid_ = valid_;
      result.relay_ = relay_;
      result.status_ = status_;
      result.timestamp_ = timestamp_;
      result.version_ = version_;
      result.rebuilding_ = rebuilding_;
      result.realSpace_ = realSpace_;
      result.tx_ = tx_;
      result.rx_ = rx_;
      result.ext_ = ext_;
      result.uspaces_ = internalGetUspaces();
      result.uspaces_.makeImmutable();
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.yottachain.nodemgmt.pb.NodeMsg) {
        return mergeFrom((io.yottachain.nodemgmt.pb.NodeMsg)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.yottachain.nodemgmt.pb.NodeMsg other) {
      if (other == io.yottachain.nodemgmt.pb.NodeMsg.getDefaultInstance()) return this;
      if (other.getID() != 0) {
        setID(other.getID());
      }
      if (!other.getNodeID().isEmpty()) {
        nodeID_ = other.nodeID_;
        onChanged();
      }
      if (!other.getPubKey().isEmpty()) {
        pubKey_ = other.pubKey_;
        onChanged();
      }
      if (!other.getOwner().isEmpty()) {
        owner_ = other.owner_;
        onChanged();
      }
      if (!other.getProfitAcc().isEmpty()) {
        profitAcc_ = other.profitAcc_;
        onChanged();
      }
      if (!other.getPoolID().isEmpty()) {
        poolID_ = other.poolID_;
        onChanged();
      }
      if (!other.getPoolOwner().isEmpty()) {
        poolOwner_ = other.poolOwner_;
        onChanged();
      }
      if (other.getQuota() != 0L) {
        setQuota(other.getQuota());
      }
      if (!other.addrs_.isEmpty()) {
        if (addrs_.isEmpty()) {
          addrs_ = other.addrs_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureAddrsIsMutable();
          addrs_.addAll(other.addrs_);
        }
        onChanged();
      }
      if (other.getCPU() != 0) {
        setCPU(other.getCPU());
      }
      if (other.getMemory() != 0) {
        setMemory(other.getMemory());
      }
      if (other.getBandwidth() != 0) {
        setBandwidth(other.getBandwidth());
      }
      if (other.getMaxDataSpace() != 0L) {
        setMaxDataSpace(other.getMaxDataSpace());
      }
      if (other.getAssignedSpace() != 0L) {
        setAssignedSpace(other.getAssignedSpace());
      }
      if (other.getProductiveSpace() != 0L) {
        setProductiveSpace(other.getProductiveSpace());
      }
      if (other.getUsedSpace() != 0L) {
        setUsedSpace(other.getUsedSpace());
      }
      if (other.getWeight() != 0D) {
        setWeight(other.getWeight());
      }
      if (other.getValid() != 0) {
        setValid(other.getValid());
      }
      if (other.getRelay() != 0) {
        setRelay(other.getRelay());
      }
      if (other.getStatus() != 0) {
        setStatus(other.getStatus());
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      if (other.getVersion() != 0) {
        setVersion(other.getVersion());
      }
      if (other.getRebuilding() != 0) {
        setRebuilding(other.getRebuilding());
      }
      if (other.getRealSpace() != 0L) {
        setRealSpace(other.getRealSpace());
      }
      if (other.getTx() != 0L) {
        setTx(other.getTx());
      }
      if (other.getRx() != 0L) {
        setRx(other.getRx());
      }
      if (!other.getExt().isEmpty()) {
        ext_ = other.ext_;
        onChanged();
      }
      internalGetMutableUspaces().mergeFrom(
          other.internalGetUspaces());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.yottachain.nodemgmt.pb.NodeMsg parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.yottachain.nodemgmt.pb.NodeMsg) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int iD_ ;
    /**
     * <pre>
     *data node index
     * </pre>
     *
     * <code>int32 iD = 1;</code>
     */
    public int getID() {
      return iD_;
    }
    /**
     * <pre>
     *data node index
     * </pre>
     *
     * <code>int32 iD = 1;</code>
     */
    public Builder setID(int value) {
      
      iD_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *data node index
     * </pre>
     *
     * <code>int32 iD = 1;</code>
     */
    public Builder clearID() {
      
      iD_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object nodeID_ = "";
    /**
     * <pre>
     *data node ID, generated from PubKey
     * </pre>
     *
     * <code>string nodeID = 2;</code>
     */
    public java.lang.String getNodeID() {
      java.lang.Object ref = nodeID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nodeID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *data node ID, generated from PubKey
     * </pre>
     *
     * <code>string nodeID = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNodeIDBytes() {
      java.lang.Object ref = nodeID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nodeID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *data node ID, generated from PubKey
     * </pre>
     *
     * <code>string nodeID = 2;</code>
     */
    public Builder setNodeID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nodeID_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *data node ID, generated from PubKey
     * </pre>
     *
     * <code>string nodeID = 2;</code>
     */
    public Builder clearNodeID() {
      
      nodeID_ = getDefaultInstance().getNodeID();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *data node ID, generated from PubKey
     * </pre>
     *
     * <code>string nodeID = 2;</code>
     */
    public Builder setNodeIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nodeID_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object pubKey_ = "";
    /**
     * <pre>
     *public key of data node
     * </pre>
     *
     * <code>string pubKey = 3;</code>
     */
    public java.lang.String getPubKey() {
      java.lang.Object ref = pubKey_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pubKey_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *public key of data node
     * </pre>
     *
     * <code>string pubKey = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPubKeyBytes() {
      java.lang.Object ref = pubKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pubKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *public key of data node
     * </pre>
     *
     * <code>string pubKey = 3;</code>
     */
    public Builder setPubKey(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pubKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *public key of data node
     * </pre>
     *
     * <code>string pubKey = 3;</code>
     */
    public Builder clearPubKey() {
      
      pubKey_ = getDefaultInstance().getPubKey();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *public key of data node
     * </pre>
     *
     * <code>string pubKey = 3;</code>
     */
    public Builder setPubKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      pubKey_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object owner_ = "";
    /**
     * <pre>
     *owner account of this miner
     * </pre>
     *
     * <code>string owner = 4;</code>
     */
    public java.lang.String getOwner() {
      java.lang.Object ref = owner_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        owner_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *owner account of this miner
     * </pre>
     *
     * <code>string owner = 4;</code>
     */
    public com.google.protobuf.ByteString
        getOwnerBytes() {
      java.lang.Object ref = owner_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        owner_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *owner account of this miner
     * </pre>
     *
     * <code>string owner = 4;</code>
     */
    public Builder setOwner(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      owner_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *owner account of this miner
     * </pre>
     *
     * <code>string owner = 4;</code>
     */
    public Builder clearOwner() {
      
      owner_ = getDefaultInstance().getOwner();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *owner account of this miner
     * </pre>
     *
     * <code>string owner = 4;</code>
     */
    public Builder setOwnerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      owner_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object profitAcc_ = "";
    /**
     * <pre>
     *profit account of this miner
     * </pre>
     *
     * <code>string profitAcc = 5;</code>
     */
    public java.lang.String getProfitAcc() {
      java.lang.Object ref = profitAcc_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        profitAcc_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *profit account of this miner
     * </pre>
     *
     * <code>string profitAcc = 5;</code>
     */
    public com.google.protobuf.ByteString
        getProfitAccBytes() {
      java.lang.Object ref = profitAcc_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        profitAcc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *profit account of this miner
     * </pre>
     *
     * <code>string profitAcc = 5;</code>
     */
    public Builder setProfitAcc(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      profitAcc_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *profit account of this miner
     * </pre>
     *
     * <code>string profitAcc = 5;</code>
     */
    public Builder clearProfitAcc() {
      
      profitAcc_ = getDefaultInstance().getProfitAcc();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *profit account of this miner
     * </pre>
     *
     * <code>string profitAcc = 5;</code>
     */
    public Builder setProfitAccBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      profitAcc_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object poolID_ = "";
    /**
     * <pre>
     *ID of associated miner pool
     * </pre>
     *
     * <code>string poolID = 6;</code>
     */
    public java.lang.String getPoolID() {
      java.lang.Object ref = poolID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        poolID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *ID of associated miner pool
     * </pre>
     *
     * <code>string poolID = 6;</code>
     */
    public com.google.protobuf.ByteString
        getPoolIDBytes() {
      java.lang.Object ref = poolID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        poolID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *ID of associated miner pool
     * </pre>
     *
     * <code>string poolID = 6;</code>
     */
    public Builder setPoolID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      poolID_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *ID of associated miner pool
     * </pre>
     *
     * <code>string poolID = 6;</code>
     */
    public Builder clearPoolID() {
      
      poolID_ = getDefaultInstance().getPoolID();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *ID of associated miner pool
     * </pre>
     *
     * <code>string poolID = 6;</code>
     */
    public Builder setPoolIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      poolID_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object poolOwner_ = "";
    /**
     * <pre>
     *Owner of associated miner pool
     * </pre>
     *
     * <code>string poolOwner = 7;</code>
     */
    public java.lang.String getPoolOwner() {
      java.lang.Object ref = poolOwner_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        poolOwner_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *Owner of associated miner pool
     * </pre>
     *
     * <code>string poolOwner = 7;</code>
     */
    public com.google.protobuf.ByteString
        getPoolOwnerBytes() {
      java.lang.Object ref = poolOwner_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        poolOwner_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *Owner of associated miner pool
     * </pre>
     *
     * <code>string poolOwner = 7;</code>
     */
    public Builder setPoolOwner(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      poolOwner_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *Owner of associated miner pool
     * </pre>
     *
     * <code>string poolOwner = 7;</code>
     */
    public Builder clearPoolOwner() {
      
      poolOwner_ = getDefaultInstance().getPoolOwner();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *Owner of associated miner pool
     * </pre>
     *
     * <code>string poolOwner = 7;</code>
     */
    public Builder setPoolOwnerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      poolOwner_ = value;
      onChanged();
      return this;
    }

    private long quota_ ;
    /**
     * <pre>
     *quota allocated by associated miner pool
     * </pre>
     *
     * <code>int64 quota = 8;</code>
     */
    public long getQuota() {
      return quota_;
    }
    /**
     * <pre>
     *quota allocated by associated miner pool
     * </pre>
     *
     * <code>int64 quota = 8;</code>
     */
    public Builder setQuota(long value) {
      
      quota_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *quota allocated by associated miner pool
     * </pre>
     *
     * <code>int64 quota = 8;</code>
     */
    public Builder clearQuota() {
      
      quota_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList addrs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureAddrsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        addrs_ = new com.google.protobuf.LazyStringArrayList(addrs_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <pre>
     *listening addresses of data node
     * </pre>
     *
     * <code>repeated string addrs = 9;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getAddrsList() {
      return addrs_.getUnmodifiableView();
    }
    /**
     * <pre>
     *listening addresses of data node
     * </pre>
     *
     * <code>repeated string addrs = 9;</code>
     */
    public int getAddrsCount() {
      return addrs_.size();
    }
    /**
     * <pre>
     *listening addresses of data node
     * </pre>
     *
     * <code>repeated string addrs = 9;</code>
     */
    public java.lang.String getAddrs(int index) {
      return addrs_.get(index);
    }
    /**
     * <pre>
     *listening addresses of data node
     * </pre>
     *
     * <code>repeated string addrs = 9;</code>
     */
    public com.google.protobuf.ByteString
        getAddrsBytes(int index) {
      return addrs_.getByteString(index);
    }
    /**
     * <pre>
     *listening addresses of data node
     * </pre>
     *
     * <code>repeated string addrs = 9;</code>
     */
    public Builder setAddrs(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureAddrsIsMutable();
      addrs_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *listening addresses of data node
     * </pre>
     *
     * <code>repeated string addrs = 9;</code>
     */
    public Builder addAddrs(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureAddrsIsMutable();
      addrs_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *listening addresses of data node
     * </pre>
     *
     * <code>repeated string addrs = 9;</code>
     */
    public Builder addAllAddrs(
        java.lang.Iterable<java.lang.String> values) {
      ensureAddrsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, addrs_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *listening addresses of data node
     * </pre>
     *
     * <code>repeated string addrs = 9;</code>
     */
    public Builder clearAddrs() {
      addrs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *listening addresses of data node
     * </pre>
     *
     * <code>repeated string addrs = 9;</code>
     */
    public Builder addAddrsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureAddrsIsMutable();
      addrs_.add(value);
      onChanged();
      return this;
    }

    private int cPU_ ;
    /**
     * <pre>
     *CPU usage of data node
     * </pre>
     *
     * <code>int32 cPU = 10;</code>
     */
    public int getCPU() {
      return cPU_;
    }
    /**
     * <pre>
     *CPU usage of data node
     * </pre>
     *
     * <code>int32 cPU = 10;</code>
     */
    public Builder setCPU(int value) {
      
      cPU_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *CPU usage of data node
     * </pre>
     *
     * <code>int32 cPU = 10;</code>
     */
    public Builder clearCPU() {
      
      cPU_ = 0;
      onChanged();
      return this;
    }

    private int memory_ ;
    /**
     * <pre>
     *memory usage of data node
     * </pre>
     *
     * <code>int32 memory = 11;</code>
     */
    public int getMemory() {
      return memory_;
    }
    /**
     * <pre>
     *memory usage of data node
     * </pre>
     *
     * <code>int32 memory = 11;</code>
     */
    public Builder setMemory(int value) {
      
      memory_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *memory usage of data node
     * </pre>
     *
     * <code>int32 memory = 11;</code>
     */
    public Builder clearMemory() {
      
      memory_ = 0;
      onChanged();
      return this;
    }

    private int bandwidth_ ;
    /**
     * <pre>
     *bandwidth usage of data node
     * </pre>
     *
     * <code>int32 bandwidth = 12;</code>
     */
    public int getBandwidth() {
      return bandwidth_;
    }
    /**
     * <pre>
     *bandwidth usage of data node
     * </pre>
     *
     * <code>int32 bandwidth = 12;</code>
     */
    public Builder setBandwidth(int value) {
      
      bandwidth_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *bandwidth usage of data node
     * </pre>
     *
     * <code>int32 bandwidth = 12;</code>
     */
    public Builder clearBandwidth() {
      
      bandwidth_ = 0;
      onChanged();
      return this;
    }

    private long maxDataSpace_ ;
    /**
     * <pre>
     *max space of data node
     * </pre>
     *
     * <code>int64 maxDataSpace = 13;</code>
     */
    public long getMaxDataSpace() {
      return maxDataSpace_;
    }
    /**
     * <pre>
     *max space of data node
     * </pre>
     *
     * <code>int64 maxDataSpace = 13;</code>
     */
    public Builder setMaxDataSpace(long value) {
      
      maxDataSpace_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *max space of data node
     * </pre>
     *
     * <code>int64 maxDataSpace = 13;</code>
     */
    public Builder clearMaxDataSpace() {
      
      maxDataSpace_ = 0L;
      onChanged();
      return this;
    }

    private long assignedSpace_ ;
    /**
     * <pre>
     *space assigned to YTFS
     * </pre>
     *
     * <code>int64 assignedSpace = 14;</code>
     */
    public long getAssignedSpace() {
      return assignedSpace_;
    }
    /**
     * <pre>
     *space assigned to YTFS
     * </pre>
     *
     * <code>int64 assignedSpace = 14;</code>
     */
    public Builder setAssignedSpace(long value) {
      
      assignedSpace_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *space assigned to YTFS
     * </pre>
     *
     * <code>int64 assignedSpace = 14;</code>
     */
    public Builder clearAssignedSpace() {
      
      assignedSpace_ = 0L;
      onChanged();
      return this;
    }

    private long productiveSpace_ ;
    /**
     * <pre>
     *pre-allocated space of data node
     * </pre>
     *
     * <code>int64 productiveSpace = 15;</code>
     */
    public long getProductiveSpace() {
      return productiveSpace_;
    }
    /**
     * <pre>
     *pre-allocated space of data node
     * </pre>
     *
     * <code>int64 productiveSpace = 15;</code>
     */
    public Builder setProductiveSpace(long value) {
      
      productiveSpace_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *pre-allocated space of data node
     * </pre>
     *
     * <code>int64 productiveSpace = 15;</code>
     */
    public Builder clearProductiveSpace() {
      
      productiveSpace_ = 0L;
      onChanged();
      return this;
    }

    private long usedSpace_ ;
    /**
     * <pre>
     *used space of data node
     * </pre>
     *
     * <code>int64 usedSpace = 16;</code>
     */
    public long getUsedSpace() {
      return usedSpace_;
    }
    /**
     * <pre>
     *used space of data node
     * </pre>
     *
     * <code>int64 usedSpace = 16;</code>
     */
    public Builder setUsedSpace(long value) {
      
      usedSpace_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *used space of data node
     * </pre>
     *
     * <code>int64 usedSpace = 16;</code>
     */
    public Builder clearUsedSpace() {
      
      usedSpace_ = 0L;
      onChanged();
      return this;
    }

    private double weight_ ;
    /**
     * <pre>
     *weight for allocate data node
     * </pre>
     *
     * <code>double weight = 17;</code>
     */
    public double getWeight() {
      return weight_;
    }
    /**
     * <pre>
     *weight for allocate data node
     * </pre>
     *
     * <code>double weight = 17;</code>
     */
    public Builder setWeight(double value) {
      
      weight_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *weight for allocate data node
     * </pre>
     *
     * <code>double weight = 17;</code>
     */
    public Builder clearWeight() {
      
      weight_ = 0D;
      onChanged();
      return this;
    }

    private int valid_ ;
    /**
     * <pre>
     *Is node valid
     * </pre>
     *
     * <code>int32 valid = 18;</code>
     */
    public int getValid() {
      return valid_;
    }
    /**
     * <pre>
     *Is node valid
     * </pre>
     *
     * <code>int32 valid = 18;</code>
     */
    public Builder setValid(int value) {
      
      valid_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *Is node valid
     * </pre>
     *
     * <code>int32 valid = 18;</code>
     */
    public Builder clearValid() {
      
      valid_ = 0;
      onChanged();
      return this;
    }

    private int relay_ ;
    /**
     * <pre>
     *Is relay node
     * </pre>
     *
     * <code>int32 relay = 19;</code>
     */
    public int getRelay() {
      return relay_;
    }
    /**
     * <pre>
     *Is relay node
     * </pre>
     *
     * <code>int32 relay = 19;</code>
     */
    public Builder setRelay(int value) {
      
      relay_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *Is relay node
     * </pre>
     *
     * <code>int32 relay = 19;</code>
     */
    public Builder clearRelay() {
      
      relay_ = 0;
      onChanged();
      return this;
    }

    private int status_ ;
    /**
     * <pre>
     *status code: 0 - registered 1 - active
     * </pre>
     *
     * <code>int32 status = 20;</code>
     */
    public int getStatus() {
      return status_;
    }
    /**
     * <pre>
     *status code: 0 - registered 1 - active
     * </pre>
     *
     * <code>int32 status = 20;</code>
     */
    public Builder setStatus(int value) {
      
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *status code: 0 - registered 1 - active
     * </pre>
     *
     * <code>int32 status = 20;</code>
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <pre>
     *timestamp of status updating operation
     * </pre>
     *
     * <code>int64 timestamp = 21;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <pre>
     *timestamp of status updating operation
     * </pre>
     *
     * <code>int64 timestamp = 21;</code>
     */
    public Builder setTimestamp(long value) {
      
      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *timestamp of status updating operation
     * </pre>
     *
     * <code>int64 timestamp = 21;</code>
     */
    public Builder clearTimestamp() {
      
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    private int version_ ;
    /**
     * <pre>
     *version number of miner
     * </pre>
     *
     * <code>int32 version = 22;</code>
     */
    public int getVersion() {
      return version_;
    }
    /**
     * <pre>
     *version number of miner
     * </pre>
     *
     * <code>int32 version = 22;</code>
     */
    public Builder setVersion(int value) {
      
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *version number of miner
     * </pre>
     *
     * <code>int32 version = 22;</code>
     */
    public Builder clearVersion() {
      
      version_ = 0;
      onChanged();
      return this;
    }

    private int rebuilding_ ;
    /**
     * <pre>
     *if node is under rebuilding
     * </pre>
     *
     * <code>int32 rebuilding = 23;</code>
     */
    public int getRebuilding() {
      return rebuilding_;
    }
    /**
     * <pre>
     *if node is under rebuilding
     * </pre>
     *
     * <code>int32 rebuilding = 23;</code>
     */
    public Builder setRebuilding(int value) {
      
      rebuilding_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *if node is under rebuilding
     * </pre>
     *
     * <code>int32 rebuilding = 23;</code>
     */
    public Builder clearRebuilding() {
      
      rebuilding_ = 0;
      onChanged();
      return this;
    }

    private long realSpace_ ;
    /**
     * <pre>
     *real space of miner
     * </pre>
     *
     * <code>int64 realSpace = 24;</code>
     */
    public long getRealSpace() {
      return realSpace_;
    }
    /**
     * <pre>
     *real space of miner
     * </pre>
     *
     * <code>int64 realSpace = 24;</code>
     */
    public Builder setRealSpace(long value) {
      
      realSpace_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *real space of miner
     * </pre>
     *
     * <code>int64 realSpace = 24;</code>
     */
    public Builder clearRealSpace() {
      
      realSpace_ = 0L;
      onChanged();
      return this;
    }

    private long tx_ ;
    /**
     * <pre>
     *tx
     * </pre>
     *
     * <code>int64 tx = 25;</code>
     */
    public long getTx() {
      return tx_;
    }
    /**
     * <pre>
     *tx
     * </pre>
     *
     * <code>int64 tx = 25;</code>
     */
    public Builder setTx(long value) {
      
      tx_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *tx
     * </pre>
     *
     * <code>int64 tx = 25;</code>
     */
    public Builder clearTx() {
      
      tx_ = 0L;
      onChanged();
      return this;
    }

    private long rx_ ;
    /**
     * <pre>
     *rx
     * </pre>
     *
     * <code>int64 rx = 26;</code>
     */
    public long getRx() {
      return rx_;
    }
    /**
     * <pre>
     *rx
     * </pre>
     *
     * <code>int64 rx = 26;</code>
     */
    public Builder setRx(long value) {
      
      rx_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *rx
     * </pre>
     *
     * <code>int64 rx = 26;</code>
     */
    public Builder clearRx() {
      
      rx_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object ext_ = "";
    /**
     * <pre>
     *other
     * </pre>
     *
     * <code>string ext = 27;</code>
     */
    public java.lang.String getExt() {
      java.lang.Object ref = ext_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ext_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *other
     * </pre>
     *
     * <code>string ext = 27;</code>
     */
    public com.google.protobuf.ByteString
        getExtBytes() {
      java.lang.Object ref = ext_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ext_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *other
     * </pre>
     *
     * <code>string ext = 27;</code>
     */
    public Builder setExt(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ext_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *other
     * </pre>
     *
     * <code>string ext = 27;</code>
     */
    public Builder clearExt() {
      
      ext_ = getDefaultInstance().getExt();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *other
     * </pre>
     *
     * <code>string ext = 27;</code>
     */
    public Builder setExtBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ext_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.Long> uspaces_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.Long>
    internalGetUspaces() {
      if (uspaces_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            UspacesDefaultEntryHolder.defaultEntry);
      }
      return uspaces_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.Long>
    internalGetMutableUspaces() {
      onChanged();;
      if (uspaces_ == null) {
        uspaces_ = com.google.protobuf.MapField.newMapField(
            UspacesDefaultEntryHolder.defaultEntry);
      }
      if (!uspaces_.isMutable()) {
        uspaces_ = uspaces_.copy();
      }
      return uspaces_;
    }

    public int getUspacesCount() {
      return internalGetUspaces().getMap().size();
    }
    /**
     * <pre>
     *used spaces on each SN
     * </pre>
     *
     * <code>map&lt;string, int64&gt; uspaces = 28;</code>
     */

    public boolean containsUspaces(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetUspaces().getMap().containsKey(key);
    }
    /**
     * Use {@link #getUspacesMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Long> getUspaces() {
      return getUspacesMap();
    }
    /**
     * <pre>
     *used spaces on each SN
     * </pre>
     *
     * <code>map&lt;string, int64&gt; uspaces = 28;</code>
     */

    public java.util.Map<java.lang.String, java.lang.Long> getUspacesMap() {
      return internalGetUspaces().getMap();
    }
    /**
     * <pre>
     *used spaces on each SN
     * </pre>
     *
     * <code>map&lt;string, int64&gt; uspaces = 28;</code>
     */

    public long getUspacesOrDefault(
        java.lang.String key,
        long defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.Long> map =
          internalGetUspaces().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     *used spaces on each SN
     * </pre>
     *
     * <code>map&lt;string, int64&gt; uspaces = 28;</code>
     */

    public long getUspacesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.Long> map =
          internalGetUspaces().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearUspaces() {
      internalGetMutableUspaces().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     *used spaces on each SN
     * </pre>
     *
     * <code>map&lt;string, int64&gt; uspaces = 28;</code>
     */

    public Builder removeUspaces(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableUspaces().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Long>
    getMutableUspaces() {
      return internalGetMutableUspaces().getMutableMap();
    }
    /**
     * <pre>
     *used spaces on each SN
     * </pre>
     *
     * <code>map&lt;string, int64&gt; uspaces = 28;</code>
     */
    public Builder putUspaces(
        java.lang.String key,
        long value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      
      internalGetMutableUspaces().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <pre>
     *used spaces on each SN
     * </pre>
     *
     * <code>map&lt;string, int64&gt; uspaces = 28;</code>
     */

    public Builder putAllUspaces(
        java.util.Map<java.lang.String, java.lang.Long> values) {
      internalGetMutableUspaces().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:pb.NodeMsg)
  }

  // @@protoc_insertion_point(class_scope:pb.NodeMsg)
  private static final io.yottachain.nodemgmt.pb.NodeMsg DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.yottachain.nodemgmt.pb.NodeMsg();
  }

  public static io.yottachain.nodemgmt.pb.NodeMsg getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NodeMsg>
      PARSER = new com.google.protobuf.AbstractParser<NodeMsg>() {
    @java.lang.Override
    public NodeMsg parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new NodeMsg(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<NodeMsg> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NodeMsg> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.yottachain.nodemgmt.pb.NodeMsg getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

