// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

package io.yottachain.nodemgmt.pb;

public interface SpotCheckTaskMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb.SpotCheckTaskMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 iD = 1;</code>
   */
  int getID();

  /**
   * <code>string nodeID = 2;</code>
   */
  java.lang.String getNodeID();
  /**
   * <code>string nodeID = 2;</code>
   */
  com.google.protobuf.ByteString
      getNodeIDBytes();

  /**
   * <code>string addr = 3;</code>
   */
  java.lang.String getAddr();
  /**
   * <code>string addr = 3;</code>
   */
  com.google.protobuf.ByteString
      getAddrBytes();

  /**
   * <code>string vNI = 4;</code>
   */
  java.lang.String getVNI();
  /**
   * <code>string vNI = 4;</code>
   */
  com.google.protobuf.ByteString
      getVNIBytes();
}
