// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

package io.yottachain.nodemgmt.pb;

public interface SuperNodeMsgOrBuilder extends
        // @@protoc_insertion_point(interface_extends:pb.SuperNodeMsg)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *super node index
     * </pre>
     *
     * <code>int32 iD = 1;</code>
     */
    int getID();

    /**
     * <pre>
     *super node ID, generated from PubKey
     * </pre>
     *
     * <code>string nodeID = 2;</code>
     */
    java.lang.String getNodeID();
    /**
     * <pre>
     *super node ID, generated from PubKey
     * </pre>
     *
     * <code>string nodeID = 2;</code>
     */
    com.google.protobuf.ByteString
    getNodeIDBytes();

    /**
     * <pre>
     *public key of super node
     * </pre>
     *
     * <code>string pubKey = 3;</code>
     */
    java.lang.String getPubKey();
    /**
     * <pre>
     *public key of super node
     * </pre>
     *
     * <code>string pubKey = 3;</code>
     */
    com.google.protobuf.ByteString
    getPubKeyBytes();

    /**
     * <pre>
     *private key of super node
     * </pre>
     *
     * <code>string privKey = 4;</code>
     */
    java.lang.String getPrivKey();
    /**
     * <pre>
     *private key of super node
     * </pre>
     *
     * <code>string privKey = 4;</code>
     */
    com.google.protobuf.ByteString
    getPrivKeyBytes();

    /**
     * <pre>
     *listening addresses of super node
     * </pre>
     *
     * <code>repeated string addrs = 5;</code>
     */
    java.util.List<java.lang.String>
    getAddrsList();
    /**
     * <pre>
     *listening addresses of super node
     * </pre>
     *
     * <code>repeated string addrs = 5;</code>
     */
    int getAddrsCount();
    /**
     * <pre>
     *listening addresses of super node
     * </pre>
     *
     * <code>repeated string addrs = 5;</code>
     */
    java.lang.String getAddrs(int index);
    /**
     * <pre>
     *listening addresses of super node
     * </pre>
     *
     * <code>repeated string addrs = 5;</code>
     */
    com.google.protobuf.ByteString
    getAddrsBytes(int index);
}
