// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types.proto

package io.yottachain.nodemgmt.pb;

public interface UpdateTaskStatusReqOrBuilder extends
        // @@protoc_insertion_point(interface_extends:pb.UpdateTaskStatusReq)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     */
    com.google.protobuf.ByteString
    getIdBytes();

    /**
     * <code>repeated int32 invalidNodeList = 2;</code>
     */
    java.util.List<java.lang.Integer> getInvalidNodeListList();
    /**
     * <code>repeated int32 invalidNodeList = 2;</code>
     */
    int getInvalidNodeListCount();
    /**
     * <code>repeated int32 invalidNodeList = 2;</code>
     */
    int getInvalidNodeList(int index);
}
